/* Generated by ffconf */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define LIBAV_CONFIGURATION "libav android experimental 20110821mt"
#define LIBAV_LICENSE "gpl mod"
#endif /* AVUTIL_AVCONFIG_H */
