LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

#LOCAL_APP_ABI += $(APP_ABI)
LOCAL_ARM_MODE += arm

LOCAL_MODULE    := mpcodecs

LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(FFMPEG_INCLUDE_DIR)

LOCAL_CFLAGS += -DHAVE_AV_CONFIG_H  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPIC
LOCAL_CFLAGS += $(GLOBAL_CFLAGS)

LOCAL_LDFLAGS += $(GLOBAL_LDFLAGS)
#LOCAL_LDFLAGS += -L$(NDK_APP_DST_DIR) -L$(TARGET_OUT)
LOCAL_LDFLAGS := -lz -llog

#LIBMPCODECS_SRC_FILES := $(wildcard $(LOCAL_PATH)/*.c)
#LIBMPCODECS_SRC_FILES := $(patsubst $(LOCAL_PATH)/%,%,$(LIBMPCODECS_SRC_FILES))

LIBMPCODECS_SRC_FILES := \
    img_format.c \
    mp_image.c \

#$(foreach FILE,$(LIBMPCODECS_SRC_FILES),$(echo $(FILE)))

ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
  LOCAL_CFLAGS += -fPIC
endif

LOCAL_SHARED_LIBRARIES := avutil swscale avcodec

LOCAL_SRC_FILES := \
	$(LIBMPCODECS_SRC_FILES) \


include $(BUILD_SHARED_LIBRARY)
